{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "think-cnap.fullname" . }}-secrets
  labels:
    {{- include "think-cnap.labels" . | nindent 4 }}
type: Opaque
data:
  googleClientId: {{ .Values.secrets.googleClientId | b64enc | quote }}
{{- end }}
