INSERT INTO security_controls (id, domain_id, code, text) VALUES (1, 1, 'SEC01-BP01', 'Separate workloads using accounts') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (2, 1, 'SEC01-BP02', 'Secure account root user and properties') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (3, 1, 'SEC01-BP03', 'Identify and validate control objectives') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (4, 1, 'SEC01-BP04', 'Stay up to date with security threats and recommendations') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (5, 1, 'SEC01-BP05', 'Reduce security management scope') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (6, 1, 'SEC01-BP06', 'Automate deployment of standard security controls') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (7, 1, 'SEC01-BP07', 'Identify threats and prioritize mitigations using a threat model') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (8, 1, 'SEC01-BP08', 'Evaluate and implement new security services and features regularly') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (9, 2, 'SEC02-BP01', 'Use strong sign-in mechanisms') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (10, 2, 'SEC02-BP02', 'Use temporary credentials') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (11, 2, 'SEC02-BP03', 'Store and use secrets securely') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (12, 2, 'SEC02-BP04', 'Rely on a centralized identity provider') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (13, 2, 'SEC02-BP05', 'Audit and rotate credentials periodically') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (14, 2, 'SEC02-BP06', 'Employ user groups and attributes') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (15, 2, 'SEC03-BP01', 'Define access requirements') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (16, 2, 'SEC03-BP02', 'Grant least privilege access') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (17, 2, 'SEC03-BP03', 'Establish emergency access process') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (18, 2, 'SEC03-BP04', 'Reduce permissions continuously') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (19, 2, 'SEC03-BP05', 'Define permission guardrails for your organization') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (20, 2, 'SEC03-BP06', 'Manage access based on lifecycle') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (21, 2, 'SEC03-BP07', 'Analyze public and cross-account access') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (22, 2, 'SEC03-BP08', 'Share resources securely within your organization') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (23, 2, 'SEC03-BP09', 'Share resources securely with a third party') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (24, 3, 'SEC04-BP01', 'Configure AWS logging') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (25, 3, 'SEC04-BP02', 'Capture logs, findings, and metrics in standardized locations') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (26, 3, 'SEC04-BP03', 'Correlate and enrich security alerts') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (27, 3, 'SEC04-BP04', 'Initiate remediation for non-compliant resources') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (28, 4, 'SEC05-BP01', 'Create network layers') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (29, 4, 'SEC05-BP02', 'Control traffic flow within your network layers') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (30, 4, 'SEC05-BP03', 'Implement inspection-based protection') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (31, 4, 'SEC05-BP04', 'Automate network protection') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (32, 4, 'SEC06-BP01', 'Perform vulnerability management') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (33, 4, 'SEC06-BP02', 'Provision compute from hardened images') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (34, 4, 'SEC06-BP03', 'Reduce manual management and interactive access') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (35, 4, 'SEC06-BP04', 'Validate software integrity') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (36, 4, 'SEC06-BP05', 'Automate compute protection') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (37, 5, 'SEC07-BP01', 'Understand your data classification scheme') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (38, 5, 'SEC07-BP02', 'Apply data protection controls based on data sensitivity') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (39, 5, 'SEC07-BP03', 'Automate identification and classification') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (40, 5, 'SEC07-BP04', 'Define scalable data lifecycle management') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (41, 5, 'SEC08-BP01', 'Implement secure key management') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (42, 5, 'SEC08-BP02', 'Enforce encryption at rest') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (43, 5, 'SEC08-BP03', 'Automate data at rest protection') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (44, 5, 'SEC08-BP04', 'Enforce access control') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (45, 5, 'SEC09-BP01', 'Implement secure key and certificate management') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (46, 5, 'SEC09-BP02', 'Enforce encryption in transit') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (47, 5, 'SEC09-BP03', 'Authenticate network communications') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (48, 6, 'SEC10-BP01', 'Identify key personnel and external resources') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (49, 6, 'SEC10-BP02', 'Develop incident management plans') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (50, 6, 'SEC10-BP03', 'Prepare forensic capabilities') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (51, 6, 'SEC10-BP04', 'Develop and test security incident response playbooks') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (52, 6, 'SEC10-BP05', 'Pre-provision access') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (53, 6, 'SEC10-BP06', 'Pre-deploy tools') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (54, 6, 'SEC10-BP07', 'Run simulations') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (55, 6, 'SEC10-BP08', 'Post-incident activity') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (56, 7, 'SEC11-BP01', 'Train for application security') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (57, 7, 'SEC11-BP02', 'Automate testing throughout the development and release lifecycle') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (58, 7, 'SEC11-BP03', 'Perform regular penetration testing') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (59, 7, 'SEC11-BP04', 'Conduct code reviews') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (60, 7, 'SEC11-BP05', 'Centralize services for packages and dependencies') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (61, 7, 'SEC11-BP06', 'Deploy software programmatically') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (62, 7, 'SEC11-BP07', 'Regularly assess security properties of the pipelines') ON CONFLICT (id) DO NOTHING;
INSERT INTO security_controls (id, domain_id, code, text) VALUES (63, 7, 'SEC11-BP08', 'Build a program that embeds security ownership in workload teams') ON CONFLICT (id) DO NOTHING;
